### ISSUE TITLE
IOS TACACS+ Group raise ValueError when factory set to True

### ISSUE THREAD

**Issue by clementtrebuchet** [mpenning/ciscoconfparse#64]
Hello
- I have some configuration files with  white space at the end of the string
```
(vim set list showing end of lines as $)
aaa group server tacacs+ tacacs $ <--  white space
    server xx.xx.xx.xx $
    server xx.xx.xx.xx $
    source-interface lolipop$

```

- This  not match the regexp below and raise ValueError as mm is None

```
REGEX = r'^aaa\sgroup\sserver\s(?P<protocol>\S+)\s(?P<group>\S+)$'
```

- What do you think if the regexp was like this ?

```
REGEX = r'aaa\sgroup\sserver\s(?P<protocol>\S+)\s(?P<group>\S+$|\S+)'
Match 1
Full match	0-31	`aaa group server tacacs+ tacacs`
Group `protocol`	17-24	`tacacs+`
Group `group`	25-31	`tacacs`
```
- So code would be something like this:

```

##
##-------------  IOS TACACS+ Group
##
class IOSAaaGroupServerLine(BaseCfgLine):
    def __init__(self, *args, **kwargs):
        super(IOSAaaGroupServerLine, self).__init__(*args, **kwargs)
        self.feature = 'aaa group server'
        REGEX = r'aaa\sgroup\sserver\s(?P<protocol>\S+)\s(?P<group>\S+$|\S+)'  
        # REGEX = r'^aaa\sgroup\sserver\s(?P<protocol>\S+)\s(?P<group>\S+)$'
        mm = re.search(REGEX, self.text)
        if not (mm is None):
            groups = mm.groupdict()
            self.protocol = groups.get('protocol', '')
            self.group = groups.get('group', '')
        else:
            raise ValueError
```

Thank for your work and your support, 
Regards,

**Comment by XenonR** [comment]
Hi Clement,
this was already fixed in [richardstrnad/ciscoconfparse](https://github.com/richardstrnad/ciscoconfparse) a while ago.

But anyway, thanks for reporting.

Regards

**Comment by clementtrebuchet** [comment]
Hello, 
Thank for your answer, but when you take it from [Pypi ](https://pypi.python.org/packages/ef/f6/d92615a81100f534e964acfcc642e9404a7991afefa732264e98f945f8fd/ciscoconfparse-1.2.40.tar.gz#md5=b52b399fc9b04254910dcd58ab948be5) the lib is not fixed, is it normal to have the fix in a fork or I misunderstood something.

Regards ,

**Comment by mpenning** [comment]
@clementtrebuchet let's start from the most relevant point...

A)  The code you're using comes from [ciscoconfparse/models_cisco.py](https://github.com/mpenning/ciscoconfparse/blob/master/ciscoconfparse/models_cisco.py) and there is no public documentation for it... it's not officially supported, but I am maintaining the code on a best effort basis... admittedly my best efforts have been infrequent these days as work / kids have kept me pretty occupied.  

At the top of [ciscoconfparse/models_cisco.py](https://github.com/mpenning/ciscoconfparse/blob/master/ciscoconfparse/models_cisco.py) it says:

```
### HUGE UGLY WARNING:
###   Anything in models_cisco.py could change at any time, until I remove this
###   warning.  I have good reason to believe that these methods are stable and 
###   function correctly, but I've been wrong before.  There are no unit tests
###   for this functionality yet, so I consider all this code alpha quality. 
###
###   Use models_cisco.py at your own risk.  You have been warned :-)
```

The key words above are *alpha quality*; in other words, yeah it might be broken.

B) @XenonR has been graciously responding to bugs in my stead and pointing people to his private fork... however, I would caution anyone against relying on his new APIs because I probably *will* change them... it's open-source and this stuff happens.  You're right that this bug isn't fixed in the PYPI release and sometime in the next few weeks I'll endeavor to catch up on all the ciscoconfparse activity.

**Comment by mpenning** [comment]
Fixed in 1.2.41

**Comment by clementtrebuchet** [comment]
Hello, 

Thanks for your actions and your great job.

Regards,
